name: Super-Linter

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  super-linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Super-Linter (Customized)
        uses: super-linter/super-linter@v7.4.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # DISABLE UNWANTED LINTERS (add as needed)
          DISABLE_MARKDOWN_PRETTIER: "true"     # Skip Markdown formatting
          DISABLE_YAML_PRETTIER: "true"         # Skip YAML formatting
          DISABLE_JSCPD: "true"                 # Skip copy-paste detection
          # Only run specific linters (optional)
          VALIDATE_MARKDOWN: "true"             # Still checks basic Markdown syntax
          VALIDATE_YAML: "true"                 # Still checks YAML syntax
