name: Super-Linter

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  statuses: write

jobs:
  super-linter:
    name: Lint Code Base
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Required for full git history

      - name: Run Super-Linter
        uses: super-linter/super-linter@v7.4.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Customize which linters run:
          DEFAULT_BRANCH: main
          VALIDATE_ALL_CODEBASE: true
          # To disable specific linters (if needed):
          DISABLE_MARKDOWN_PRETTIER: false  # Set to 'true' to skip markdown formatting checks
          MARKDOWN_CONFIG_FILE: .markdownlint.json  # Optional config file
